version: "3.3"

networks:
  traefik:
    external: true

services:
  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.wem.webtm.ru`)
      - traefik.http.routers.whoami.entrypoints=https
      - traefik.http.routers.whoami.tls.certresolver=letsencrypt
      - traefik.port=80
      # - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - traefik

