version: "3.3"

services:
  traefik:
    image: traefik:v2.9
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/traefik_dyn.yml:/etc/traefik/traefik_dyn.yml:ro
      - ./traefik/acme.json:/etc/traefik/acme.json
      - ./traefik/log:/var/log/traefik
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
networks:
  traefik:
    external: true
