entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
  https:
    address: ":443"

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: ponyashcat228@gmail.com
      storage: /etc/traefik/acme.json
      tlsChallenge: {}

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: traefik
    watch: true
  file:
    filename: /etc/traefik/traefik_dyn.yml
    watch: true
log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log