http:
  middlewares:
    auth:
      basicAuth:
        users:
          - <htpasswd -bn user password>
  routers:
    api:
      entryPoints:
        - https
      rule: Host(`<dns_name>`)
      service: api@internal
      middlewares:
        - auth
      tls:
        certResolver: letsencrypt
        options: onlytls13

tls:
  options:
    onlytls13:
      minVersion: VersionTLS12
